auth_basico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/',include('usuarios.urls')),
    path('',include('home.urls')),
    path('feed/',include('feed.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='feed'
urlpatterns = [
        path('homepage/',views.homepage ,name='homepage'),
        path('sair/', views.sair , name='sair'),
        path('@<str:usuario_solicitado>/', views.perfil, name='perfil'),
        path('upload_post/', views.upload_post, name='upload_post'),
        path('excluir_post/<int:post_id>/', views.excluir_post, name='excluir_post'),
        path('upload_comentario/<int:post_id>/', views.upload_comentario, name='upload_comentario'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
        path('',views.home ,name='home'),

    ]

usuarios/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='usuarios'

urlpatterns = [
        path('login/', views.login, name='login'),
        path('cadastro/',views.cadastro, name='cadastro'),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):   

    #atribuindo um post a um usuario e on_delete cascade= usario deletado, posts deletados. 
    autor = models.ForeignKey(User,on_delete=models.CASCADE)
    conteudo = models.TextField()
    postado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Postado por {self.autor.username}"
    
    @classmethod
    def obter_posts_do_usuario(cls,username):
        user = User.objects.get(username=username)
        posts_do_usuario = Post.objects.filter(autor=user)
        return posts_do_usuario.order_by('-postado')

        
    def get_dataformatada(self):
        now = timezone.now()
        time_difference = now - self.postado

        if time_difference < timedelta(minutes=1):
            return "Agora mesmo."
        elif time_difference < timedelta(hours=1):
            minutes = int(time_difference.total_seconds() // 60)
            return f"{minutes} min"
        elif time_difference < timedelta(days=1):
            hours = int(time_difference.total_seconds() // 3600)
            return f"{hours} h"
        else:
            days = time_difference.days
            return f"{days} d "

class Comentario(models.Model):
    post = models.ForeignKey(Post, related_name='comentarios', on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    conteudo = models.TextField()
    postado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentário por {self.autor.username} em {self.post.titulo}"

    def get_dataformatada(self):
        now = timezone.now()
        time_difference = now - self.postado

        if time_difference < timedelta(minutes=1):
            return "Agora mesmo."
        elif time_difference < timedelta(hours=1):
            minutes = int(time_difference.total_seconds() // 60)
            return f"{minutes} min"
        elif time_difference < timedelta(days=1):
            hours = int(time_difference.total_seconds() // 3600)
            return f"{hours} h"
        else:
            days = time_difference.days
            return f"{days} d "

home/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.CASCADE)
    imagem_perfil= models.ImageField(upload_to='imagens_perfil/',blank=True,null=True)

    def __str__(self):
        return self.user.username

feed/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Post, Comentario
from django.http import HttpResponse, JsonResponse



@login_required(login_url='usuarios:login')
def homepage(request):
    user = request.user
    posts = Post.objects.order_by('-postado') #ordenandos os posts dos mais novos,pro mais velhos   
    usuarios = User.objects.all()
    perfil = request.user.perfil
    imagem_perfil_url = perfil.imagem_perfil.url
    contexto = {'imagem_perfil_url': imagem_perfil_url,'user':user, 'usuarios':usuarios, 'posts':posts}
    return render(request, 'homepage.html', contexto)


def sair (request):
    request.session.flush()
    return redirect('home:home')

@login_required(login_url='usuarios:login')
def perfil(request,usuario_solicitado):
    usuario_perfil = User.objects.get(username=usuario_solicitado)
    posts_usuario = Post.obter_posts_do_usuario(usuario_solicitado)
    contexto = {'usuario_perfil':usuario_perfil   ,'posts_do_usuario': posts_usuario }
    return render(request,'perfil.html',contexto)

@login_required(login_url='usuarios:login')
def upload_post(request):
    if request.method == 'POST':
        txt_post= request.POST.get('texto_conteudo')
        autor_post = request.user
        post = Post.objects.create(autor=autor_post, conteudo=txt_post)
        return redirect('feed:homepage')
    else:
        return redirect('feed:meuperfil')
    
@login_required(login_url='usuario:login')
def excluir_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('feed:homepage')
    else:
        return HttpResponse("Vtmnccc")



@login_required(login_url='usuarios:login')
def upload_comentario(request,post_id):
    if request.method== 'POST':
        conteudo_comentario = request.POST.get('conteudo_comentario')
        autor_comentario = request.user 
        post_comentado =  get_object_or_404(Post, id=post_id)
        comentario = Comentario.objects.create(autor=autor_comentario, conteudo=conteudo_comentario, post=post_comentado)
        return redirect('feed:homepage')
    else:
        return HttpResponse("Vtmnccc")

home/views.py
from django.shortcuts import render

def home(request):
 
    return render(request, 'home.html')

usuarios/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from .models import Perfil
from django.core.files.storage import default_storage
from django.utils.text import slugify


def cadastro(request):
    if request.method=="GET":
        return render(request, 'cadastro.html')
    else:
        usuario = request.POST.get('usuario')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        nome =  request.POST.get('nome')
        imagem_perfil = request.FILES.get('imagem_perfil')

        user = User.objects.filter(username=usuario).first()
        if user:
            return HttpResponse("Já existe um usuário com esse usuário.")
        
        user = User.objects.create_user(username=usuario, email=email, password=senha, first_name=nome)

        if imagem_perfil:
            nome_imagem = slugify(user.username) + '.jpg'
            caminho_imagem = default_storage.save('imagens_perfil/' + nome_imagem, imagem_perfil)
            perfil, criado = Perfil.objects.get_or_create(usuario=user)
            perfil.imagem_perfil = caminho_imagem
            perfil.save() 

        return redirect ('usuarios:login')

def login(request):
    if request.method=="GET":
        return render(request, 'login.html')
    else:
        usario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usario,password=senha)

        if user:
            login_django (request,user)
            return redirect('feed:homepage') 
        else:
            return HttpResponse("Usuario ou senha inválido")

        

feed/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'feed/css/feed.css'%}">
    <title>Faculbook</title>
</head>
<body>
    
    <header> 
        <div class="logo"><h1>Faculbook</h1></div>
        <a href="{% url 'feed:perfil' request.user.username %}"><div class="infos"> 
            <div>  {% if user.perfil.imagem_perfil %}
                <img src="{{user.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
            {% endif %}  <h4>{{user.username}}</h4></div></a>
        <a href="{% url 'feed:sair' %}">Sair</a></div>
    </header>
    <main>
        <div class="direitaMain">
            <h4>Todos usuários</h4>    
           <ul>
            {% for usuario in usuarios %} 
                {% if usuario != request.user %}
                <div>
                    {% if usuario.perfil.imagem_perfil %}
                                  <img id="foto_post" src="{{ usuario.perfil.imagem_perfil.url }}" alt="Foto de perfil de {{ post.autor.username }}">
                              {% else %}
                                  <img id="foto_post" src="{% static 'caminho/para/imagem_padrao.jpg' %}" alt="Foto de perfil padrão">
                              {% endif %}
                 <a href="{% url 'feed:perfil' usuario.username %}"> <li>{{ usuario.username }}</li></div></a>
                {% endif %}
            {% endfor %}
        </ul> 
                
            </div>
    
           <div class="meioMain">
                <div class="novo_post">

                    <h1>Nova Publicação </h1>
                    <form action="{% url 'feed:upload_post' %}"  class="form_msg" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                    <textarea required name="texto_conteudo" placeholder="Oque você tem para compartilhar?"  class="area_text" id="texto" cols="30" rows="5"></textarea>
                    <input type="submit" class="enviar_texto" value="Enviar">
                    </form>
            </div>

                <div class="conteudo">
                {%for post in posts %}

                <div class="post">
                    <div class="post_cabecalho">

                        {%if request.user.username == post.autor.username%}
                         <form action="{% url 'feed:excluir_post' post.id %}"  class="form_msg btn_excluir" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <button>Exluir</button>
                        </form>   
                        {%endif%}


                        {% if post.autor.perfil.imagem_perfil %}
                        <img src="{{ post.autor.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
                        {% endif %} 
                        <div class="informacoes_usuario_post">
                            <h2>{{post.autor.first_name}} - @{{post.autor.username}}</h2>
                            <h4>{{post.get_dataformatada}}</h4>
                        </div>     
                    </div>
                    <div class="post_conteudo">
                        <p>{{post.conteudo}}</p>
                    </div>

                    <div id="post_comentarios" class="post_comentarios">
                        
                        {% for comentario in post.comentarios.all %}

                            <div class="comentario">  
                                {% if comentario.autor.perfil.imagem_perfil %}
                                <img src="{{ comentario.autor.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
                            {% endif %}  
                                    <div class="comentario_informacoes">
                                        <h3>{{comentario.autor.first_name}} - @{{comentario.autor.username}}</h3>
                                        <p>{{comentario.conteudo}}</p>
                                        
                                    </div>
                            </div>

                        {%endfor%}
                    </div>
 
                    <form  class="form_enviarComentario"  action="{% url 'feed:upload_comentario' post.id %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea   required     placeholder="Comente..."  name="conteudo_comentario" ></textarea>
                        <input id="enviar_comentario" type="submit" value="comentar">
                    </form>

                </div>

                {%endfor%}
                </div>
           
           </div>
    </main>

</body>

</html>

feed/templates/perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'feed/css/perfil.css'%}">
    <title>Faculbook</title>
</head>
<body>
    <header> 
        <div class="logo"><a href="{% url 'feed:homepage' %}"><h1>Faculbook</h1></a></div>
        <a href="{% url 'feed:perfil' request.user.username %}"><div class="infos"> 
            <div>  {% if user.perfil.imagem_perfil %}
                <img src="{{user.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
            {% endif %}  <h4>{{user.username}}</h4></div></a>
        <a href="{% url 'feed:sair' %}">Sair</a></div>
    </header>
    
    <main>
        <div class="informacoes_perfil">

            {% if user.perfil.imagem_perfil %}
                <img src="{{usuario_perfil.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
            {% endif %}
            
            <h1> {{usuario_perfil.first_name.capitalize}} - @{{usuario_perfil.username}}</h1>

        </div>


        <div class="posts_usuario">
            <h1>Posts de {{usuario_perfil.first_name.capitalize}}</h1>
        {%for post in posts_do_usuario %}

        <div class="post">
            <div class="post_cabecalho">
                {% if post.autor.perfil.imagem_perfil %}
                <img src="{{ post.autor.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
                {% endif %} 
                <div class="informacoes_usuario_post">
                    <h2>{{post.autor.first_name}} - @{{post.autor.username}}</h2>
                    <h4>{{post.get_dataformatada}}</h4>
                </div>     
            </div>
            <div class="post_conteudo">
                <p>{{post.conteudo}}</p>
            </div>
            <div class="post_comentarios">
                
                {% for comentario in post.comentarios.all %}

                <div class="comentario">
                   
                    {% if comentario.autor.perfil.imagem_perfil %}
                    <img src="{{ comentario.autor.perfil.imagem_perfil.url }}" alt="Imagem de Perfil">
                {% endif %}  
                        <div class="comentario_informacoes">
                            <h3>{{comentario.autor.first_name}} - @{{comentario.autor.username}}</h3>
                            <p>{{comentario.conteudo}}</p>
                            
                        </div>

                    
                
                </div>
                {%endfor%}

            </div>

            <form  class="form_enviarComentario"  action="{% url 'feed:upload_comentario' post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <textarea   required     placeholder="Comente..."  name="conteudo_comentario" ></textarea>
                <input type="submit" value="comentar">
            </form>

        </div>

        {%endfor%}
    </div>

    </main>

</body>
</html>

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facultech - Home </title>
    <link rel="stylesheet" href="{% static 'home/css/home.css'%}">
</head>
<body>
    {% if user.is_authenticated %}
        <script>window.location.href = "{% url 'feed:homepage' %}";</script>
    {% else %}
    <header class="cabeçalho">
      
         <h1>FACULbook</h1>
        <div class="login_cadastro">  <a href="{% url 'usuarios:login' %}"> <button>Entrar</button></a>
            <a href="{% url 'usuarios:cadastro' %}"> <button>Criar conta</button> </a>
        </div>
    </header>
    <div class="slider">
        <div class="conteudo">
            <h1>Faculbook</h1>
    <p>O <span>Faculbook </span>é uma rede social projetada exclusivamente para a comunidade acadêmica. Esta rede social foi desenvolvida com o 
        objetivo de promover a interação entre alunos da instituição.</p>
    </div>
    <img src="{% static 'home/imgs/faeterj.jpg'%}" class="img_Fundo" alt="faeterj">

    </div>
    {% endif %}
   
</body>
</html>

usuarios/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Faculbook- Cadastro</title>
    <link rel="stylesheet" href="{% static 'usuarios/css/cadastro.css'%}">
</head>
<body>
    {% if user.is_authenticated %}
        <script>window.location.href = "{% url 'feed:homepage' %}";</script>
    {% else %}
    <header>
        <a href="{% url 'home:home' %}">  <h1>Faculbook</h1></a>
    </header>

   <main>

    <h1>Cadastro</h1>
    <form action="{% url 'usuarios:cadastro' %}" method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="usuario" placeholder="Usuario">
        <br>
        <input type="text" name="nome" placeholder="Primeiro Nome">
        <br>
        <input type="email"   name="email"  placeholder="Email">
        <br>
        <input type="password" name="senha" placeholder="Senha">
        <br>
        <input type="file" name="imagem_perfil" accept="image/*">
        <br>
        <input type="submit" value="Cadastrar"">
    </form>
   </main>

   <footer>

    <h1>@jaolvz</h1>
   </footer>

   {% endif %}
</body>
</html>

usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'usuarios/css/login.css'%}">
    <title>Faculbook - Login</title>
</head>
<body>
    {% if user.is_authenticated %}
        <script>window.location.href = "{% url 'feed:homepage' %}";</script>
    {% else %}

    <header>
          <a href="{% url 'home:home' %}">  <h1>Faculbook</h1></a>
    </header>
<main>
    
<h1>login</h1>
    <form action="{% url 'usuarios:login' %}" method="POST" >
        {% csrf_token %}
        <input type="text" name="usuario" placeholder="Usuario">
        <br>
        <input type="password" name="senha" placeholder="Senha">
        <br>
        <input type="submit" value="Login"">
    </form>
</main>

    <footer> <h1>João Vitor Gonçalves de Oliveira</h1></footer>
    {% endif %}
</body>
</html>